# Generated by Django 4.1.1 on 2022-11-16 08:49

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("products", "0002_cart"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="cart",
            options={
                "verbose_name": "Корзина",
                "verbose_name_plural": "Корзина",
            },
        ),
        migrations.AlterUniqueTogether(
            name="cart",
            unique_together={("user", "product")},
        ),
    ]
