# Generated by Django 4.1.1 on 2023-02-26 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0003_alter_cart_options_alter_cart_unique_together"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="image",
            field=models.ImageField(
                default=None,
                null=True,
                upload_to="products/images/",
                verbose_name="Фото",
            ),
        ),
    ]
